In [1]:
import pandas as pd
import sqlite3

In [32]:
con.close()

In [2]:
con = sqlite3.connect("../dataset/data.db")

In [34]:
query = """select * from BASE_MODELO_FULL_FEAT_ENG"""
df = pd.read_sql_query(query , con)
df.shape

(461074, 22)

In [35]:
df.columns

Index(['id_lector', 'id_libro', 'fecha_interaccion', 'rating', 'nombre_lector',
       'genero', 'vive_en', 'nacimiento', 'titulo', 'autor', 'genero_libro',
       'editorial', 'anio_edicion', 'resumen', 'volumen_lectura',
       'rating_promedio_crudo', 'rating_promedio_usuario_te',
       'desviacion_estandar_rating', 'genero_favorito_usuario',
       'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos'],
      dtype='str')

In [42]:
FEATURES=['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro',
       'editorial', 'anio_edicion', 'volumen_lectura', 'rating_promedio_usuario_te',
       'desviacion_estandar_rating', 'genero_favorito_usuario',
       'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
dic_features = {k:1 for k in FEATURES}
dic_features

{'genero': 1,
 'vive_en': 1,
 'nacimiento': 1,
 'autor': 1,
 'genero_libro': 1,
 'editorial': 1,
 'anio_edicion': 1,
 'volumen_lectura': 1,
 'rating_promedio_usuario_te': 1,
 'desviacion_estandar_rating': 1,
 'genero_favorito_usuario': 1,
 'cant_antiguos': 1,
 'cant_nuevos': 1,
 'ratio_libros_antiguos_vs_nuevos': 1}

In [44]:
dic_features_2={'genero': 1,
 'vive_en': 0,
 'nacimiento': 1,
 'autor': 0,
 'genero_libro': 1,
 'editorial': 0,
 'anio_edicion': 1,
 'volumen_lectura': 1,
 'rating_promedio_usuario_te': 0,
 'desviacion_estandar_rating': 1,
 'genero_favorito_usuario': 0,
 'cant_antiguos': 1,
 'cant_nuevos': 0,
 'ratio_libros_antiguos_vs_nuevos': 1}

In [53]:
df.rating.isna().sum()

np.int64(0)

In [55]:
count=0
for id_lector, grupo in df.groupby('id_lector'):
    # NDCG solo tiene sentido si hay al menos 2 items para rankear
    if len(grupo) <= 1:
        # scikit-learn espera listas dentro de listas para esto: [y_true], [y_pred]
        #print(id_lector)
        count+=1
print(count)

1770

In [52]:
df.columns.to_list()

['id_lector',
 'id_libro',
 'fecha_interaccion',
 'rating',
 'nombre_lector',
 'genero',
 'vive_en',
 'nacimiento',
 'titulo',
 'autor',
 'genero_libro',
 'editorial',
 'anio_edicion',
 'resumen',
 'volumen_lectura',
 'rating_promedio_crudo',
 'rating_promedio_usuario_te',
 'desviacion_estandar_rating',
 'genero_favorito_usuario',
 'cant_antiguos',
 'cant_nuevos',
 'ratio_libros_antiguos_vs_nuevos']

In [48]:
[c for c,v in dic_features_2.items() if v==1 ]

['genero',
 'nacimiento',
 'genero_libro',
 'anio_edicion',
 'volumen_lectura',
 'desviacion_estandar_rating',
 'cant_antiguos',
 'ratio_libros_antiguos_vs_nuevos']

In [40]:
[c for c in df.columns if c not in features]

['id_lector', 'id_libro', 'nombre_lector', 'resumen']

In [36]:
df.dtypes

id_lector                              str
id_libro                               str
fecha_interaccion                      str
rating                               int64
nombre_lector                          str
genero                                 str
vive_en                                str
nacimiento                           int64
titulo                                 str
autor                                  str
genero_libro                           str
editorial                              str
anio_edicion                         int64
resumen                                str
volumen_lectura                      int64
rating_promedio_crudo              float64
rating_promedio_usuario_te         float64
desviacion_estandar_rating         float64
genero_favorito_usuario                str
cant_antiguos                        int64
cant_nuevos                          int64
ratio_libros_antiguos_vs_nuevos    float64
dtype: object

In [7]:
query = """select * from BASE_MODELO_FULL"""
df = pd.read_sql_query(query , con)
df.shape

(461074, 14)

In [8]:
df.dtypes

id_lector              str
id_libro               str
fecha_interaccion      str
rating               int64
nombre_lector          str
genero                 str
vive_en                str
nacimiento           int64
titulo                 str
autor                  str
genero_libro           str
editorial              str
anio_edicion         int64
resumen                str
dtype: object

In [9]:
df.anio_edicion.describe()

count    461074.000000
mean       2005.759119
std          90.490527
min           0.000000
25%        2006.000000
50%        2009.000000
75%        2014.000000
max        2025.000000
Name: anio_edicion, dtype: float64

In [23]:
df.loc[df["anio_edicion"]<1800,'anio_edicion'].value_counts()

anio_edicion
0      928
201      3
1        1
Name: count, dtype: int64

In [26]:
df.loc[df["anio_edicion"]>1800,'anio_edicion'].describe()

count    460142.000000
mean       2009.820395
std           6.711048
min        1835.000000
25%        2006.000000
50%        2009.000000
75%        2014.000000
max        2025.000000
Name: anio_edicion, dtype: float64

In [12]:
df.anio_edicion.value_counts(dropna=False)

anio_edicion
2007    50429
2006    33965
2009    33787
2008    30129
2011    30113
        ...
1892        1
1899        1
1939        1
1888        1
1922        1
Name: count, Length: 114, dtype: int64

# CUANTOS libros han leido cada id

In [5]:
df.head(1)

,id_lector,id_libro,fecha_interaccion,rating,nombre_lector,genero,vive_en,nacimiento,titulo,autor,genero_libro,editorial,anio_edicion,resumen
0,bioaqua,las-puertas-de-anubis,12-01-2019,4,raul,Hombre,San javier - España,1976,LAS PUERTAS DE ANUBIS,"POWERS, TIM","Fantástica, ciencia ficción",GIGAMESH,2015,"Brendan Doyle, un profesor de literatura espec..."

In [6]:
df[['id_lector','id_libro']].drop_duplicates().shape

(461074, 2)

In [7]:
df.shape

(461074, 14)

In [11]:
cantidad_libros_por_lector = df.groupby('id_lector').agg(
    libros_por_lector = ('id_libro','count')
).value_counts(dropna=False)
cantidad_libros_por_lector.to_csv("../outputs/notebooks/01/cantidades_libros_por_lector.csv")

In [20]:
df.groupby('id_lector').agg(
    libros_por_lector = ('id_libro','count')
).describe()

       libros_por_lector
count       10667.000000
mean           43.224337
std           101.115278
min             1.000000
25%             2.000000
50%             9.000000
75%            41.000000
max          2260.000000

In [18]:
cantidad_libros_por_lector.describe()

count     476.000000
mean       22.409664
std       106.265478
min         1.000000
25%         1.000000
50%         3.000000
75%        10.000000
max      1770.000000
Name: count, dtype: float64

In [16]:
cantidad_lector_por_libros = df.groupby('id_libro').agg(
    libros_por_lector = ('id_lector','count')
).value_counts(dropna=False)
cantidad_libros_por_lector.to_csv("../outputs/notebooks/01/cantidad_lector_por_libros.csv")

Entonces, el plan de pasar el id del cliente no me parece bueno. Mas que pasar su dni, hay que pasar su adn. En vez de quien es, pasarle su perfil.

Ideas de feat eng : 
- Variables de comportamiento : 
    - rating_promedio_usuario : ¿Es un crítico exigente que suele poner 4, o es generoso y pone 9?
    - volumen_lectura : Cantidad total de libros calificados (esto ayuda al modelo a tratar diferente a un lector hardcore que a uno de un solo libro)
    - desviacion_estandar_rating: ¿Sus notas varían mucho o siempre pone lo mismo?
- Variables de afinidad
    - genero_favorito_usuario: El género de libro que más lee.
    - ratio_libros_antiguos_vs_nuevos: Si tiende a leer clásicos o novedades (usando anio_edicion).
Nota para el caso de 1 solo libro: Para los lectores con una sola interacción, su rating_promedio será exactamente la nota de ese único libro. Esto puede causar leakage (fuga de información) durante el entrenamiento. Se suele calcular el promedio excluyendo la fila actual, o rellenando con el promedio global de la base.

- Target encoding
Si de todas formas quieres que el modelo use explícitamente el ID para capturar algún efecto específico de ese usuario que las otras variables no explican, no puedes usar One-Hot Encoding (tendrías miles de columnas vacías) ni Label Encoding (el árbol interpretará que el lector 100 vale el doble que el 50).

Puedes usar Target Encoding: reemplazar el id_lector por la media del rating que ese lector suele dar.
Para resolver tu preocupación sobre los usuarios con un solo libro, es obligatorio aplicar una fórmula de suavizado. El suavizado tira el promedio del usuario hacia el promedio global de todos los lectores si el usuario tiene muy pocos datos.

In [21]:
df.anio_edicion.describe()

count     461074
unique       117
top         2007
freq       50429
Name: anio_edicion, dtype: int64

In [22]:
df.nacimiento.describe()

count     461074
unique        94
top
freq      115127
Name: nacimiento, dtype: object

In [23]:
df.nacimiento.value_counts()

nacimiento
        115127
1910     21305
1981     13762
1980     13734
1973     11384
         ...
2013         2
1936         1
1912         1
1924         1
1931         1
Name: count, Length: 94, dtype: int64